# fly.toml app configuration file generated for aniol-rodriguez-202409-back on 2024-12-15T19:24:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aniol-rodriguez-202409-back'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
